In [1]:

library(cubature)
library(MASS)
library(pracma)
library(mvtnorm)

library(LogConcDEAD)
library(logcondens) 


Warning message:
“no DISPLAY variable so Tk is not available”


In [2]:
source('lcic.r')

Package 'mclust' version 6.0.1
Type 'citation("mclust")' for citing this R package in publications.


Attaching package: ‘mclust’


The following object is masked from ‘package:mvtnorm’:

    dmvnorm




In [3]:
all_split_r_vals <- seq(from=0.1, to=0.9, by=0.1)


### Test $d=2$

In [ ]:

d <- 2
n <- 2000
Sigma_max <- 15
eigensep <- 1
num_repeats_full <- 5
savefilename <- 'Results/split_r_exp_gaussian_d=2_.RData'
all_split_r_vals <- seq(from=0.1, to=0.9, by=0.1)

my_results <- tests_for_split_ratio_r_gaussian(d, n, all_split_r_vals, Sigma_max, eigensep, num_repeats_full, savefilename)

[1] "Num r values and experiment repeats:"
[1] 9
[1] 5
[1] "r index and repeat index:"
[1] 1
[1] 1
[1] "Diagonal covariance: "
     [,1] [,2]
[1,]   15    0
[2,]    0   14
[1] "PCA done!"
[1] "Marginal: "
[1] 1
[1] "Marginal: "
[1] 2
[1] "Done experiment"
[1] 1
[1] "r index and repeat index:"
[1] 1
[1] 2
[1] "Diagonal covariance: "
     [,1] [,2]
[1,]   15    0
[2,]    0   14
[1] "PCA done!"
[1] "Marginal: "
[1] 1
[1] "Marginal: "
[1] 2
[1] "Done experiment"
[1] 2
[1] "r index and repeat index:"
[1] 1
[1] 3
[1] "Diagonal covariance: "
     [,1] [,2]
[1,]   15    0
[2,]    0   14
[1] "PCA done!"
[1] "Marginal: "
[1] 1
[1] "Marginal: "
[1] 2
[1] "Done experiment"
[1] 3
[1] "r index and repeat index:"
[1] 1
[1] 4
[1] "Diagonal covariance: "
     [,1] [,2]
[1,]   15    0
[2,]    0   14
[1] "PCA done!"
[1] "Marginal: "
[1] 1
[1] "Marginal: "
[1] 2
[1] "Done experiment"
[1] 4
[1] "r index and repeat index:"
[1] 1
[1] 5
[1] "Diagonal covariance: "
     [,1] [,2]
[1,]   15    0
[2,]    0   14


In [5]:
my_results

[[1]]
[[1]]$n
[1] 2000

[[1]]$d
[1] 2

[[1]]$split_r
[1] 0.1

[[1]]$irep
[1] 1

[[1]]$ip_mat
            [,1]       [,2]
Comp.1 0.7856838  0.6186282
Comp.2 0.6186282 -0.7856838

[[1]]$hell_err_mean_logcondens
[1] 0.002308149


[[2]]
[[2]]$n
[1] 2000

[[2]]$d
[1] 2

[[2]]$split_r
[1] 0.1

[[2]]$irep
[1] 2

[[2]]$ip_mat
             [,1]      [,2]
Comp.1 -0.1428428 0.9897454
Comp.2  0.9897454 0.1428428

[[2]]$hell_err_mean_logcondens
[1] 0.00223264


[[3]]
[[3]]$n
[1] 2000

[[3]]$d
[1] 2

[[3]]$split_r
[1] 0.1

[[3]]$irep
[1] 3

[[3]]$ip_mat
             [,1]      [,2]
Comp.1  0.9625690 0.2710368
Comp.2 -0.2710368 0.9625690

[[3]]$hell_err_mean_logcondens
[1] 0.002238778


[[4]]
[[4]]$n
[1] 2000

[[4]]$d
[1] 2

[[4]]$split_r
[1] 0.1

[[4]]$irep
[1] 4

[[4]]$ip_mat
            [,1]       [,2]
Comp.1 0.6569399 -0.7539429
Comp.2 0.7539429  0.6569399

[[4]]$hell_err_mean_logcondens
[1] 0.002590443


[[5]]
[[5]]$n
[1] 2000

[[5]]$d
[1] 2

[[5]]$split_r
[1] 0.1

[[5]]$irep
[1] 5

[[5]]$ip_mat
             [,1]        [,2]
Comp.1 0.99885762 -0.04778555
Comp.2 0.04778555  0.99885762

[[5]]$hell_err_mean_logcondens
[1] 0.002030624


[[6]]
[[6]]$n
[1] 2000

[[6]]$d
[1] 2

[[6]]$split_r
[1] 0.2

[[6]]$irep
[1] 1

[[6]]$ip_mat
             [,1]      [,2]
Comp.1  0.7163404 0.6977510
Comp.2 -0.6977510 0.7163404

[[6]]$hell_err_mean_logcondens
[1] 0.003831286


[[7]]
[[7]]$n
[1] 2000

[[7]]$d
[1] 2

[[7]]$split_r
[1] 0.2

[[7]]$irep
[1] 2

[[7]]$ip_mat
            [,1]       [,2]
Comp.1 0.9685086 -0.2489800
Comp.2 0.2489800  0.9685086

[[7]]$hell_err_mean_logcondens
[1] 0.003244948


[[8]]
[[8]]$n
[1] 2000

[[8]]$d
[1] 2

[[8]]$split_r
[1] 0.2

[[8]]$irep
[1] 3

[[8]]$ip_mat
             [,1]      [,2]
Comp.1  0.9685072 0.2489857
Comp.2 -0.2489857 0.9685072

[[8]]$hell_err_mean_logcondens
[1] 0.005006884


[[9]]
[[9]]$n
[1] 2000

[[9]]$d
[1] 2

[[9]]$split_r
[1] 0.2

[[9]]$irep
[1] 4

[[9]]$ip_mat
            [,1]       [,2]
Comp.1 0.8765182 -0.4813687
Comp.2 0.4813687  0.8765182

[[9]]$hell_err_mean_logcondens
[1] 0.003570331


[[10]]
[[10]]$n
[1] 2000

[[10]]$d
[1] 2

[[10]]$split_r
[1] 0.2

[[10]]$irep
[1] 5

[[10]]$ip_mat
            [,1]       [,2]
Comp.1 0.1600550  0.9871081
Comp.2 0.9871081 -0.1600550

[[10]]$hell_err_mean_logcondens
[1] 0.001513505


[[11]]
[[11]]$n
[1] 2000

[[11]]$d
[1] 2

[[11]]$split_r
[1] 0.3

[[11]]$irep
[1] 1

[[11]]$ip_mat
            [,1]       [,2]
Comp.1 0.9880892 -0.1538825
Comp.2 0.1538825  0.9880892

[[11]]$hell_err_mean_logcondens
[1] 0.001983638


[[12]]
[[12]]$n
[1] 2000

[[12]]$d
[1] 2

[[12]]$split_r
[1] 0.3

[[12]]$irep
[1] 2

[[12]]$ip_mat
             [,1]      [,2]
Comp.1  0.8705920 0.4920056
Comp.2 -0.4920056 0.8705920

[[12]]$hell_err_mean_logcondens
[1] 0.003465065


[[13]]
[[13]]$n
[1] 2000

[[13]]$d
[1] 2

[[13]]$split_r
[1] 0.3

[[13]]$irep
[1] 3

[[13]]$ip_mat
             [,1]      [,2]
Comp.1  0.6632054 0.7484375
Comp.2 -0.7484375 0.6632054

[[13]]$hell_err_mean_logcondens
[1] 0.003000087


[[14]]
[[14]]$n
[1] 2000

[[14]]$d
[1] 2

[[14]]$split_r
[1] 0.3

[[14]]$irep
[1] 4

[[14]]$ip_mat
             [,1]      [,2]
Comp.1  0.9154126 0.4025168
Comp.2 -0.4025168 0.9154126

[[14]]$hell_err_mean_logcondens
[1] 0.004087067


[[15]]
[[15]]$n
[1] 2000

[[15]]$d
[1] 2

[[15]]$split_r
[1] 0.3

[[15]]$irep
[1] 5

[[15]]$ip_mat
            [,1]       [,2]
Comp.1 0.6895803  0.7242092
Comp.2 0.7242092 -0.6895803

[[15]]$hell_err_mean_logcondens
[1] 0.003244914


[[16]]
[[16]]$n
[1] 2000

[[16]]$d
[1] 2

[[16]]$split_r
[1] 0.4

[[16]]$irep
[1] 1

[[16]]$ip_mat
            [,1]       [,2]
Comp.1 0.9055762 -0.4241837
Comp.2 0.4241837  0.9055762

[[16]]$hell_err_mean_logcondens
[1] 0.005015306


[[17]]
[[17]]$n
[1] 2000

[[17]]$d
[1] 2

[[17]]$split_r
[1] 0.4

[[17]]$irep
[1] 2

[[17]]$ip_mat
            [,1]       [,2]
Comp.1 0.7963748  0.6048034
Comp.2 0.6048034 -0.7963748

[[17]]$hell_err_mean_logcondens
[1] 0.004567869


[[18]]
[[18]]$n
[1] 2000

[[18]]$d
[1] 2

[[18]]$split_r
[1] 0.4

[[18]]$irep
[1

In [7]:
retrieved_data <- readRDS('Results/split_r_exp_gaussian_d=2_.RData')
retrieved_data

[[1]]
[[1]]$n
[1] 2000

[[1]]$d
[1] 2

[[1]]$split_r
[1] 0.1

[[1]]$irep
[1] 1

[[1]]$ip_mat
            [,1]       [,2]
Comp.1 0.7856838  0.6186282
Comp.2 0.6186282 -0.7856838

[[1]]$hell_err_mean_logcondens
[1] 0.002308149


[[2]]
[[2]]$n
[1] 2000

[[2]]$d
[1] 2

[[2]]$split_r
[1] 0.1

[[2]]$irep
[1] 2

[[2]]$ip_mat
             [,1]      [,2]
Comp.1 -0.1428428 0.9897454
Comp.2  0.9897454 0.1428428

[[2]]$hell_err_mean_logcondens
[1] 0.00223264


[[3]]
[[3]]$n
[1] 2000

[[3]]$d
[1] 2

[[3]]$split_r
[1] 0.1

[[3]]$irep
[1] 3

[[3]]$ip_mat
             [,1]      [,2]
Comp.1  0.9625690 0.2710368
Comp.2 -0.2710368 0.9625690

[[3]]$hell_err_mean_logcondens
[1] 0.002238778


[[4]]
[[4]]$n
[1] 2000

[[4]]$d
[1] 2

[[4]]$split_r
[1] 0.1

[[4]]$irep
[1] 4

[[4]]$ip_mat
            [,1]       [,2]
Comp.1 0.6569399 -0.7539429
Comp.2 0.7539429  0.6569399

[[4]]$hell_err_mean_logcondens
[1] 0.002590443


[[5]]
[[5]]$n
[1] 2000

[[5]]$d
[1] 2

[[5]]$split_r
[1] 0.1

[[5]]$irep
[1] 5

[[5]]$ip_mat
             [,1]        [,2]
Comp.1 0.99885762 -0.04778555
Comp.2 0.04778555  0.99885762

[[5]]$hell_err_mean_logcondens
[1] 0.002030624


[[6]]
[[6]]$n
[1] 2000

[[6]]$d
[1] 2

[[6]]$split_r
[1] 0.2

[[6]]$irep
[1] 1

[[6]]$ip_mat
             [,1]      [,2]
Comp.1  0.7163404 0.6977510
Comp.2 -0.6977510 0.7163404

[[6]]$hell_err_mean_logcondens
[1] 0.003831286


[[7]]
[[7]]$n
[1] 2000

[[7]]$d
[1] 2

[[7]]$split_r
[1] 0.2

[[7]]$irep
[1] 2

[[7]]$ip_mat
            [,1]       [,2]
Comp.1 0.9685086 -0.2489800
Comp.2 0.2489800  0.9685086

[[7]]$hell_err_mean_logcondens
[1] 0.003244948


[[8]]
[[8]]$n
[1] 2000

[[8]]$d
[1] 2

[[8]]$split_r
[1] 0.2

[[8]]$irep
[1] 3

[[8]]$ip_mat
             [,1]      [,2]
Comp.1  0.9685072 0.2489857
Comp.2 -0.2489857 0.9685072

[[8]]$hell_err_mean_logcondens
[1] 0.005006884


[[9]]
[[9]]$n
[1] 2000

[[9]]$d
[1] 2

[[9]]$split_r
[1] 0.2

[[9]]$irep
[1] 4

[[9]]$ip_mat
            [,1]       [,2]
Comp.1 0.8765182 -0.4813687
Comp.2 0.4813687  0.8765182

[[9]]$hell_err_mean_logcondens
[1] 0.003570331


[[10]]
[[10]]$n
[1] 2000

[[10]]$d
[1] 2

[[10]]$split_r
[1] 0.2

[[10]]$irep
[1] 5

[[10]]$ip_mat
            [,1]       [,2]
Comp.1 0.1600550  0.9871081
Comp.2 0.9871081 -0.1600550

[[10]]$hell_err_mean_logcondens
[1] 0.001513505


[[11]]
[[11]]$n
[1] 2000

[[11]]$d
[1] 2

[[11]]$split_r
[1] 0.3

[[11]]$irep
[1] 1

[[11]]$ip_mat
            [,1]       [,2]
Comp.1 0.9880892 -0.1538825
Comp.2 0.1538825  0.9880892

[[11]]$hell_err_mean_logcondens
[1] 0.001983638


[[12]]
[[12]]$n
[1] 2000

[[12]]$d
[1] 2

[[12]]$split_r
[1] 0.3

[[12]]$irep
[1] 2

[[12]]$ip_mat
             [,1]      [,2]
Comp.1  0.8705920 0.4920056
Comp.2 -0.4920056 0.8705920

[[12]]$hell_err_mean_logcondens
[1] 0.003465065


[[13]]
[[13]]$n
[1] 2000

[[13]]$d
[1] 2

[[13]]$split_r
[1] 0.3

[[13]]$irep
[1] 3

[[13]]$ip_mat
             [,1]      [,2]
Comp.1  0.6632054 0.7484375
Comp.2 -0.7484375 0.6632054

[[13]]$hell_err_mean_logcondens
[1] 0.003000087


[[14]]
[[14]]$n
[1] 2000

[[14]]$d
[1] 2

[[14]]$split_r
[1] 0.3

[[14]]$irep
[1] 4

[[14]]$ip_mat
             [,1]      [,2]
Comp.1  0.9154126 0.4025168
Comp.2 -0.4025168 0.9154126

[[14]]$hell_err_mean_logcondens
[1] 0.004087067


[[15]]
[[15]]$n
[1] 2000

[[15]]$d
[1] 2

[[15]]$split_r
[1] 0.3

[[15]]$irep
[1] 5

[[15]]$ip_mat
            [,1]       [,2]
Comp.1 0.6895803  0.7242092
Comp.2 0.7242092 -0.6895803

[[15]]$hell_err_mean_logcondens
[1] 0.003244914


[[16]]
[[16]]$n
[1] 2000

[[16]]$d
[1] 2

[[16]]$split_r
[1] 0.4

[[16]]$irep
[1] 1

[[16]]$ip_mat
            [,1]       [,2]
Comp.1 0.9055762 -0.4241837
Comp.2 0.4241837  0.9055762

[[16]]$hell_err_mean_logcondens
[1] 0.005015306


[[17]]
[[17]]$n
[1] 2000

[[17]]$d
[1] 2

[[17]]$split_r
[1] 0.4

[[17]]$irep
[1] 2

[[17]]$ip_mat
            [,1]       [,2]
Comp.1 0.7963748  0.6048034
Comp.2 0.6048034 -0.7963748

[[17]]$hell_err_mean_logcondens
[1] 0.004567869


[[18]]
[[18]]$n
[1] 2000

[[18]]$d
[1] 2

[[18]]$split_r
[1] 0.4

[[18]]$irep
[1

### Test $d=3$

In [8]:

d <- 3
n <- 2000
Sigma_max <- 15
eigensep <- 1
num_repeats_full <- 5
savefilename <- 'Results/split_r_exp_gaussian_d=3_.RData'
all_split_r_vals <- seq(from=0.1, to=0.9, by=0.1)

my_results <- tests_for_split_ratio_r_gaussian(d, n, all_split_r_vals, Sigma_max, eigensep, num_repeats_full, savefilename)

[1] "Num r values and experiment repeats:"
[1] 9
[1] 5
[1] "r index and repeat index:"
[1] 1
[1] 1
[1] "Diagonal covariance: "
     [,1] [,2] [,3]
[1,]   15    0    0
[2,]    0   14    0
[3,]    0    0   13
[1] "PCA done!"
[1] "Marginal: "
[1] 1
[1] "Marginal: "
[1] 2
[1] "Marginal: "
[1] 3
[1] "Done experiment"
[1] 1
[1] "r index and repeat index:"
[1] 1
[1] 2
[1] "Diagonal covariance: "
     [,1] [,2] [,3]
[1,]   15    0    0
[2,]    0   14    0
[3,]    0    0   13
[1] "PCA done!"
[1] "Marginal: "
[1] 1
[1] "Marginal: "
[1] 2
[1] "Marginal: "
[1] 3
[1] "Done experiment"
[1] 2
[1] "r index and repeat index:"
[1] 1
[1] 3
[1] "Diagonal covariance: "
     [,1] [,2] [,3]
[1,]   15    0    0
[2,]    0   14    0
[3,]    0    0   13
[1] "PCA done!"
[1] "Marginal: "
[1] 1
[1] "Marginal: "
[1] 2
[1] "Marginal: "
[1] 3
[1] "Done experiment"
[1] 6
[1] "r index and repeat index:"
[1] 2
[1] 2
[1] "Diagonal covariance: "
     [,1] [,2] [,3]
[1,]   15    0    0
[2,]    0   14    0
[3,]    0    0   1

In [9]:

for (d in 4:10) {
    n <- 2000
    Sigma_max <- 15
    eigensep <- 1
    num_repeats_full <- 5
    savefilename <- sprintf('Results/split_r_exp_gaussian_d=%s_.RData', d)
    all_split_r_vals <- seq(from=0.1, to=0.9, by=0.1)
    
    my_results <- tests_for_split_ratio_r_gaussian(d, n, all_split_r_vals, Sigma_max, eigensep, num_repeats_full, savefilename)
    
}



[1] "Num r values and experiment repeats:"
[1] 9
[1] 5
[1] "r index and repeat index:"
[1] 1
[1] 1
[1] "Diagonal covariance: "
     [,1] [,2] [,3] [,4]
[1,]   15    0    0    0
[2,]    0   14    0    0
[3,]    0    0   13    0
[4,]    0    0    0   12
[1] "PCA done!"
[1] "Marginal: "
[1] 1
[1] "Marginal: "
[1] 2
[1] "Marginal: "
[1] 3
[1] "Marginal: "
[1] 4
[1] "Done experiment"
[1] 1
[1] "r index and repeat index:"
[1] 1
[1] 2
[1] "Diagonal covariance: "
     [,1] [,2] [,3] [,4]
[1,]   15    0    0    0
[2,]    0   14    0    0
[3,]    0    0   13    0
[4,]    0    0    0   12
[1] "PCA done!"
[1] "Marginal: "
[1] 1
[1] "Marginal: "
[1] 2
[1] "Marginal: "
[1] 3
[1] "Marginal: "
[1] 4
[1] "Done experiment"
[1] 2
[1] "r index and repeat index:"
[1] 1
[1] 3
[1] "Diagonal covariance: "
     [,1] [,2] [,3] [,4]
[1,]   15    0    0    0
[2,]    0   14    0    0
[3,]    0    0   13    0
[4,]    0    0    0   12
[1] "PCA done!"
[1] "Marginal: "
[1] 1
[1] "Marginal: "
[1] 2
[1] "Marginal: "
[1]

In [26]:
d <- 15
n <- 2000
Sigma_max <- 15
eigensep <- 1
num_repeats_full <- 5
savefilename <- 'Results/split_r_exp_gaussian_d=15_.RData'
all_split_r_vals <- seq(from=0.1, to=0.9, by=0.1)

my_results <- tests_for_split_ratio_r_gaussian(d, n, all_split_r_vals, Sigma_max, eigensep, num_repeats_full, savefilename)

[1] "Num r values and experiment repeats:"
[1] 9
[1] 5
[1] "r index and repeat index:"
[1] 1
[1] 1
[1] "Diagonal covariance: "
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]   15    0    0    0    0    0    0    0    0     0     0     0     0
 [2,]    0   14    0    0    0    0    0    0    0     0     0     0     0
 [3,]    0    0   13    0    0    0    0    0    0     0     0     0     0
 [4,]    0    0    0   12    0    0    0    0    0     0     0     0     0
 [5,]    0    0    0    0   11    0    0    0    0     0     0     0     0
 [6,]    0    0    0    0    0   10    0    0    0     0     0     0     0
 [7,]    0    0    0    0    0    0    9    0    0     0     0     0     0
 [8,]    0    0    0    0    0    0    0    8    0     0     0     0     0
 [9,]    0    0    0    0    0    0    0    0    7     0     0     0     0
[10,]    0    0    0    0    0    0    0    0    0     6     0     0     0
[11,]    0    0    0    0    0    0    0    0   

In [4]:


convert_to_matrix <- function(retrieved_data) {

    # Convert to matrix
    num_exp = length(retrieved_data)
    
    results_mat <- matrix(nrow=num_exp ,ncol=5)
    colnames(results_mat) <- c("n", "d", "split_r", "irep", "hell_err_mean_logcondens")
    
    for (eind in 1:num_exp){
        results_mat[eind, "n"] <- retrieved_data[[eind]]$n
        results_mat[eind, "d"] <- retrieved_data[[eind]]$d
        results_mat[eind, "split_r"] <- retrieved_data[[eind]]$split_r
        results_mat[eind, "irep"] <- retrieved_data[[eind]]$irep
        results_mat[eind, "hell_err_mean_logcondens"] <- retrieved_data[[eind]]$hell_err_mean_logcondens
    }
    return(results_mat)
}

get_ave_err <- function(results_mat, all_split_r_vals){
    num_r_vals <- length(all_split_r_vals)
    ave_err_vec <- rep(0,num_r_vals)
    for (rvind in 1:num_r_vals){
        where_r <- (results_mat[,"split_r"]==all_split_r_vals[rvind])
        ave_err_vec[rvind] <- mean(results_mat[where_r,"hell_err_mean_logcondens"])
    }
    return(ave_err_vec)
}

In [4]:
# retrieved_data
retrieved_data_d5 <- readRDS('Results/split_r_exp_gaussian_d=5_.RData')
retrieved_data_d10 <- readRDS('Results/split_r_exp_gaussian_d=10_.RData')
retrieved_data_d15 <- readRDS('Results/split_r_exp_gaussian_d=15_.RData')



results_mat_d5 <- convert_to_matrix(retrieved_data_d5)
results_mat_d10 <- convert_to_matrix(retrieved_data_d10)
results_mat_d15 <- convert_to_matrix(retrieved_data_d15)



In [12]:

pdf(file='Results/split-r-figures/all_three.pdf', width=15, height=5)
options(repr.plot.width = 15, repr.plot.height = 5)
par(mfrow = c(1, 3), mar=c(6,6,4,2))

point_alpha <- 0.3
line_alpha <- 1
pch <- 19
lty <- 1

plot(x=results_mat_d5[,"split_r"], results_mat_d5[,"hell_err_mean_logcondens"], pch=pch, col=rgb(0,0,1,point_alpha), main=expression(d == 5),
     cex.lab=2, cex.axis=1.5, cex.main=2.5, xlab=expression(r), ylab="Squared hellinger error", ylim=c(0,0.13))
lines(x=all_split_r_vals, y=get_ave_err(results_mat_d5, all_split_r_vals), lty=lty, col=rgb(0,0,1,line_alpha))
###
plot(x=results_mat_d10[,"split_r"], results_mat_d10[,"hell_err_mean_logcondens"], pch=pch, col=rgb(0,0,1,point_alpha), main=expression(d == 10),
     cex.lab=2, cex.axis=1.5, cex.main=2.5, xlab=expression(r), ylab="Squared hellinger error", ylim=c(0,0.13))
lines(x=all_split_r_vals, y=get_ave_err(results_mat_d10, all_split_r_vals), lty=lty, col=rgb(0,0,1,line_alpha))
###
plot(x=results_mat_d15[,"split_r"], results_mat_d15[,"hell_err_mean_logcondens"], pch=pch, col=rgb(0,0,1,point_alpha), main=expression(d == 15),
     cex.lab=2, cex.axis=1.5, cex.main=2.5, xlab=expression(r), ylab="Squared hellinger error", ylim=c(0,0.13))
lines(x=all_split_r_vals, y=get_ave_err(results_mat_d15, all_split_r_vals), lty=lty, col=rgb(0,0,1,line_alpha))
###
dev.off()

png 
  2

In [34]:
# mean(results_mat[results_mat[,"split_r"]==0.1,"hell_err_mean_logcondens"])

[1] 0.07110591

In [13]:
# retrieved_data
retrieved_data_d2 <- readRDS('Results/split_r_exp_gaussian_d=2_.RData')
retrieved_data_d3 <- readRDS('Results/split_r_exp_gaussian_d=3_.RData')
retrieved_data_d4 <- readRDS('Results/split_r_exp_gaussian_d=4_.RData')
retrieved_data_d5 <- readRDS('Results/split_r_exp_gaussian_d=5_.RData')
retrieved_data_d6 <- readRDS('Results/split_r_exp_gaussian_d=6_.RData')
retrieved_data_d7 <- readRDS('Results/split_r_exp_gaussian_d=7_.RData')
retrieved_data_d8 <- readRDS('Results/split_r_exp_gaussian_d=8_.RData')
retrieved_data_d9 <- readRDS('Results/split_r_exp_gaussian_d=9_.RData')
retrieved_data_d10 <- readRDS('Results/split_r_exp_gaussian_d=10_.RData')
retrieved_data_d15 <- readRDS('Results/split_r_exp_gaussian_d=15_.RData')


results_mat_d2 <- convert_to_matrix(retrieved_data_d2)
results_mat_d3 <- convert_to_matrix(retrieved_data_d3)
results_mat_d4 <- convert_to_matrix(retrieved_data_d4)
results_mat_d5 <- convert_to_matrix(retrieved_data_d5)
results_mat_d6 <- convert_to_matrix(retrieved_data_d6)
results_mat_d7 <- convert_to_matrix(retrieved_data_d7)
results_mat_d8 <- convert_to_matrix(retrieved_data_d8)
results_mat_d9 <- convert_to_matrix(retrieved_data_d9)
results_mat_d10 <- convert_to_matrix(retrieved_data_d10)
results_mat_d15 <- convert_to_matrix(retrieved_data_d15)

In [14]:
all_split_r_vals[which.min(get_ave_err(results_mat_d2, all_split_r_vals))]
all_split_r_vals[which.min(get_ave_err(results_mat_d3, all_split_r_vals))]
all_split_r_vals[which.min(get_ave_err(results_mat_d4, all_split_r_vals))]
all_split_r_vals[which.min(get_ave_err(results_mat_d5, all_split_r_vals))]
all_split_r_vals[which.min(get_ave_err(results_mat_d6, all_split_r_vals))]
all_split_r_vals[which.min(get_ave_err(results_mat_d7, all_split_r_vals))]
all_split_r_vals[which.min(get_ave_err(results_mat_d8, all_split_r_vals))]
all_split_r_vals[which.min(get_ave_err(results_mat_d9, all_split_r_vals))]
all_split_r_vals[which.min(get_ave_err(results_mat_d10, all_split_r_vals))]
all_split_r_vals[which.min(get_ave_err(results_mat_d15, all_split_r_vals))]

[1] 0.1

[1] 0.1

[1] 0.1

[1] 0.1

[1] 0.2

[1] 0.2

[1] 0.3

[1] 0.3

[1] 0.3

[1] 0.4

In [7]:
results_mat_d2

n    d split_r irep hell_err_mean_logcondens
 [1,] 2000 2 0.1     1    0.002308149             
 [2,] 2000 2 0.1     2    0.002232640             
 [3,] 2000 2 0.1     3    0.002238778             
 [4,] 2000 2 0.1     4    0.002590443             
 [5,] 2000 2 0.1     5    0.002030624             
 [6,] 2000 2 0.2     1    0.003831286             
 [7,] 2000 2 0.2     2    0.003244948             
 [8,] 2000 2 0.2     3    0.005006884             
 [9,] 2000 2 0.2     4    0.003570331             
[10,] 2000 2 0.2     5    0.001513505             
[11,] 2000 2 0.3     1    0.001983638             
[12,] 2000 2 0.3     2    0.003465065             
[13,] 2000 2 0.3     3    0.003000087             
[14,] 2000 2 0.3     4    0.004087067             
[15,] 2000 2 0.3     5    0.003244914             
[16,] 2000 2 0.4     1    0.005015306             
[17,] 2000 2 0.4     2    0.004567869             
[18,] 2000 2 0.4     3    0.004792160             
[19,] 2000 2 0.4     4    0.004943180             
[20,] 2000 2 0.4     5    0.004312839             
[21,] 2000 2 0.5     1    0.005823438             
[22,] 2000 2 0.5     2    0.003038156             
[23,] 2000 2 0.5     3    0.006806984             
[24,] 2000 2 0.5     4    0.006039884             
[25,] 2000 2 0.5     5    0.003163091             
[26,] 2000 2 0.6     1    0.004409800             
[27,] 2000 2 0.6     2    0.005324598             
[28,] 2000 2 0.6     3    0.003900385             
[29,] 2000 2 0.6     4    0.005449952             
[30,] 2000 2 0.6     5    0.003830507             
[31,] 2000 2 0.7     1    0.004635682             
[32,] 2000 2 0.7     2    0.003445784             
[33,] 2000 2 0.7     3    0.004923695             
[34,] 2000 2 0.7     4    0.005156699             
[35,] 2000 2 0.7     5    0.005105663             
[36,] 2000 2 0.8     1    0.005380356             
[37,] 2000 2 0.8     2    0.007280987             
[38,] 2000 2 0.8     3    0.006873704             
[39,] 2000 2 0.8     4    0.006000240             
[40,] 2000 2 0.8     5    0.015103412             
[41,] 2000 2 0.9     1    0.016148353             
[42,] 2000 2 0.9     2    0.012930319             
[43,] 2000 2 0.9     3    0.016869682             
[44,] 2000 2 0.9     4    0.019142298             
[45,] 2000 2 0.9     5    0.015474787

In [45]:
?plotmath

plotmath               package:grDevices               R Documentation

_M_a_t_h_e_m_a_t_i_c_a_l _A_n_n_o_t_a_t_i_o_n _i_n _R

_D_e_s_c_r_i_p_t_i_o_n:

     If the ‘text’ argument to one of the text-drawing functions
     (‘text’, ‘mtext’, ‘axis’, ‘legend’) in R is an expression, the
     argument is interpreted as a mathematical expression and the
     output will be formatted according to TeX-like rules.  Expressions
     can also be used for titles, subtitles and x- and y-axis labels
     (but not for axis labels on ‘persp’ plots).

     In most cases other language objects (names and calls, including
     formulas) are coerced to expressions and so can also be used.

_D_e_t_a_i_l_s:

     A mathematical expression must obey the normal rules of syntax for
     any R expression, but it is interpreted according to very
     different rules than for normal R expressions.

     It is possible to produce many different mathematical symbols,
     generate sub- or superscripts, produce fractions, etc.

     The output from ‘demo(plotmath)’ includes several tables which
     show the available features.  In these tables, the columns of grey
     text show sample R expressions, and the columns of black text show
     the resulting output.

     The available features are also described in the tables below:

       *Syntax*                             *Meaning*                               
       ‘x + y’                              x plus y                                
       ‘x - y’                              x minus y                               
       ‘x*y’                                juxtapose x and y                       
       ‘x/y’                                x forwardslash y                        
       ‘x %+-% y’                           x plus or minus y                       
       ‘x %/% y’                            x divided by y                          
       ‘x %*% y’                            x times y                               
       ‘x %.% y’                            x cdot y                                
       ‘x[i]’                               x subscript i                           
       ‘x^2’                                x superscript 2                         
       ‘paste(x, y, z)’                     juxtapose x, y, and z                   
       ‘sqrt(x)’                            square root of x                        
       ‘sqrt(x, y)’                         yth root of x                           
       ‘x == y’                             x equals y                              
       ‘x != y’                             x is not equal to y                     
       ‘x < y’                              x is less than y                        
       ‘x <= y’                             x is less than or equal to y            
       ‘x > y’                              x is greater than y                     
       ‘x >= y’                             x is greater than or equal to y         
       ‘!x’                                 not x                                   
       ‘x %~~% y’                           x is approximately equal to y           
       ‘x %=~% y’                           x and y are congruent                   
       ‘x %==% y’                           x is defined as y                       
       ‘x %prop% y’                         x is proportional to y                  
       ‘x %~% y’                            x is distributed as y                   
       ‘plain(x)’                           draw x in normal font                   
       ‘bold(x)’                            draw x in bold font                     
       ‘italic(x)’                          draw x in italic font                   
       ‘bolditalic(x)’                      draw x in bolditalic font               
       ‘symbol(x)’                          draw x in symbol font                   