In [7]:
# library(logcondens)
# library(cubature)
# install.packages('logcondens')
# install.packages('FNN')

Warning message in install.packages("FNN"):
“installation of package ‘FNN’ had non-zero exit status”
Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done



In [1]:
# library(logcondens)
# library('FNN')
library(MASS)

In [2]:
library(pracma)

In [6]:
Q = randortho(3, type="orthonormal")
Q

[,1]       [,2]       [,3]      
[1,] -0.4281078  0.4025512  0.8091206
[2,] -0.3376685  0.7592198 -0.5563860
[3,] -0.8382742 -0.5114077 -0.1890991

In [7]:
t(Q)

[,1]       [,2]       [,3]      
[1,] -0.4281078 -0.3376685 -0.8382742
[2,]  0.4025512  0.7592198 -0.5114077
[3,]  0.8091206 -0.5563860 -0.1890991

In [22]:
print(Q %*% t(Q))

              [,1]          [,2]         [,3]
[1,]  1.000000e+00 -1.024332e-17 7.915263e-19
[2,] -1.024332e-17  1.000000e+00 5.567992e-18
[3,]  7.915263e-19  5.567992e-18 1.000000e+00


In [16]:
prod(diag(Q))

[1] 0.06146248

In [13]:
print(Q[1,]%*%Q[2,])

              [,1]
[1,] -1.110223e-16


In [14]:
d <- 3
M = matrix(0, ncol = d, nrow = d)
print(M)
diag(M) <- c(4,5,6)
print(M)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0
     [,1] [,2] [,3]
[1,]    4    0    0
[2,]    0    5    0
[3,]    0    0    6


In [17]:
1.1*c(1:5)

[1] 1.1 2.2 3.3 4.4 5.5

In [19]:
print("Check")
print(M)

[1] "Check"
     [,1] [,2] [,3]
[1,]    4    0    0
[2,]    0    5    0
[3,]    0    0    6


In [17]:
prod(c(1,2,3))

[1] 6

In [19]:
Q

[,1]       [,2]       [,3]      
[1,] -0.4281078  0.4025512  0.8091206
[2,] -0.3376685  0.7592198 -0.5563860
[3,] -0.8382742 -0.5114077 -0.1890991

In [18]:
Q*pi

[,1]      [,2]      [,3]      
[1,] -1.344940  1.264652  2.5419275
[2,] -1.060817  2.385159 -1.7479380
[3,] -2.633516 -1.606635 -0.5940722